version: "{build}"
build: off
shallow_clone: true
clone_folder: c:\phpexcel-stream
skip_tags: true

environment:
  matrix:
    - nodejs_version: 0.10

install:
  - cinst php
  - cd c:\tools\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_sqlite3.dll >> php.ini
  - SET PATH=C:\tools\php;%PATH%
  - cd C:\phpexcel-stream
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - echo @php "%~dp0composer.phar" %*>composer.bat
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - tape test/*.js
