version: "{build}"
build: off
shallow_clone: true
clone_folder: c:\phpexcel-stream
skip_tags: true

environment:
  matrix:
    - nodejs_version: 0.10

install:
  - cinst php -y
  - cd c:\tools\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - SET PATH=C:\tools\php;%PATH%
  - cd C:\phpexcel-stream
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install

test_script:
  - node --version
  - npm --version
  - tape test/*.js
